apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/tough-artwork-368615/gke-terraform
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: "mongodb-service"
        - name: MONGO_PORT
          value: "27017"
        - name: SERVICE_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  type: LoadBalancer  
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app
